Repository balancednetwork/balanced-network-interface, pull requests merged in 2021-12, with the labels that each got.

#811 Change Wallet display in Swap to 4 dp
  src/app/components/trade/SwapPanel.tsx
Labels: review

#810 feat: reposition notification for small devices
  src/app/components/Notification/NotificationContainer.tsx
Labels: UX Review Complete, discussion

#812 feat: add proper empty states
  src/app/components/home/TransactionPanel.tsx
  src/app/components/home/WalletPanel.tsx
Labels: review, UX Review Complete

#792 feat: add rebalancing modal
  src/app/components/Modal/index.tsx
  src/app/components/Tooltip/index.tsx
  src/app/components/home/LoanPanel.tsx
  src/app/components/home/PositionDetailPanel.tsx
  src/assets/images/rebalancing-above.svg
  src/assets/images/rebalancing-below.svg
Labels: review, UX Review Complete

#814 Fix: <for> transaction fails for queue
  src/types/balanced-v1-sdk/entities/trade.ts
Labels: review, UX Review Complete

#817 Update - new API backend
  src/packages/BalancedJs/chain.ts
Labels: review

#831 fix: add missing minimumReceive to swapICX
  src/app/components/trade/SwapPanel.tsx
  src/packages/BalancedJs/contracts/Router.ts
  src/utils/index.ts
Labels: review
