Repository balancednetwork/balanced-network-interface, pull requests merged in 2021-09, with the labels that each got.

#651 feat: update favicon
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon16.png
  public/favicon32.png
  public/index.html
Labels: review, UX Review Complete

#628 Fix: update proposal metadata
  src/app/components/ProposalStatusIcon/index.tsx
  src/utils/timeformat.ts
Labels: review, UX Review Complete, Code Review Complete

#659 fix rebalancing ui text
  src/app/components/home/PositionDetailPanel.tsx
Labels: review

#648 Vote Page: Add "New Proposal" Button & Proposal Types
  src/app/components/Button/index.tsx
  src/app/components/List/index.tsx
  src/app/components/Popover/index.tsx
  src/app/components/Tooltip/index.tsx
  src/app/components/newproposal/ProposalTypesSelect.tsx
  src/app/components/newproposal/RatioInput.tsx
  src/app/containers/NewProposalPage/constant.ts
  src/app/containers/NewProposalPage/index.tsx
  src/app/containers/ProposalPage/Ratio.tsx
  src/app/containers/ProposalPage/index.tsx
  src/app/containers/VotePage/index.tsx
  src/packages/BalancedJs/addresses.ts
  src/packages/BalancedJs/contracts/BALN.ts
  src/packages/BalancedJs/contracts/Dividends.ts
  src/packages/BalancedJs/contracts/Governance.ts
  src/packages/BalancedJs/contracts/Rebalancing.ts
  src/packages/BalancedJs/index.ts
  src/queries/vote/index.ts
  src/types/index.ts
Labels: wip

#645 feat: add notification to vote menu item
  src/app/components/AppBar/index.tsx
  src/app/components/ProposalInfo/index.tsx
  src/app/containers/VotePage/index.tsx
  src/queries/queryKeys.ts
  src/queries/vote/index.ts
Labels: review, UX Review Complete, Code Review Complete

#683 Feat: add exchange warning to sICX send confirmation
  src/app/components/home/wallets/SendPanel.tsx
Labels: review, UX Review Complete

#691 fix/refactor network id uses
  src/app/components/Header/index.tsx
  src/app/components/home/TransactionPanel.tsx
  src/constants/currency.ts
  src/packages/BalancedJs/addresses.ts
  src/packages/BalancedJs/chain.ts
  src/packages/BalancedJs/contractSettings.ts
  src/packages/BalancedJs/contracts/contract.ts
  src/packages/BalancedJs/index.ts
  src/packages/icon-react/index.tsx
  src/queries/vote/index.ts
  src/store/transactions/actions.ts
  src/utils/index.ts
Labels: review

#695 Feat: add content to the OMM liquidity pools
  src/app/components/trade/LPDescription.tsx
Labels: review, UX Review Complete

#684 fix: rename gradient ids in stably logo
  src/assets/tokens/USDS.svg
Labels: review
