Repository balancednetwork/balanced-network-interface, pull requests merged in 2021-07, with the labels that each got.

#552 feat: add confirm modals in rewards panel
  src/app/components/home/RewardsPanel.tsx
  src/store/reward/hooks.ts
Labels: UX Review Complete, review

#544 fix: add animations to wallet expansion
  src/app/components/home/WalletPanel.tsx
Labels: Code Review Complete, UX Review Complete, review

#503 feat: 🎸 add tooltip minimum supply
  .gitignore
  src/app/components/Form/index.tsx
  src/app/components/Popover/index.tsx
  src/app/components/Tooltip/index.tsx
  src/app/components/home/LoanPanel.tsx
  src/app/components/trade/LPPanel.tsx
Labels: review

#550 fix: Ledger Integration/#333 Prevent users from interacting with UI
  .gitignore
  package.json
  src/app/components/Header/index.tsx
  src/app/components/WalletModal/index.tsx
  src/app/components/home/CollateralPanel.tsx
  src/app/components/home/DividendVote.tsx
  src/app/components/home/LoanPanel.tsx
  src/app/components/home/RewardsPanel.tsx
  src/app/components/home/wallets/BALNWallet/StakePanel.tsx
  src/app/components/home/wallets/SICXWallet/DepositPanel.tsx
  src/app/components/home/wallets/SICXWallet/UnstakePanel.tsx
  src/app/components/home/wallets/SendPanel.tsx
  src/app/components/trade/LiquidityDetails.tsx
  src/app/components/trade/ReturnICDSection.tsx
  src/app/components/trade/SupplyLiquidityModal.tsx
  src/app/components/trade/SwapPanel.tsx
  src/app/containers/Airdrip/index.tsx
  src/utils/messages.ts
  yarn.lock
Labels: UX Review Complete, review

#454 fix: sliders and text inputs for collateral and loans sections
  src/app/components/Form/index.tsx
  src/app/components/home/CollateralPanel.tsx
  src/app/components/home/LoanPanel.tsx
  src/store/collateral/hooks.ts
  src/store/loan/hooks.ts
Labels: review

#562 Fix: change risk ratio bar color when passing "All Collateral Locked"
  src/app/components/home/PositionDetailPanel.tsx
Labels: UX Review Complete, review

#426 fix: Update meta tags for home and trade page
  public/img-preview/home.png
  public/img-preview/trade.png
  public/index.html
  public/safari-pinned-tab.svg
  src/app/index.tsx
Labels: Code Review Complete, UX Review Complete, review

#572 Fix/#567 Re-request transport while user try to change wallet
  src/app/components/Header/index.tsx
  src/app/components/WalletModal/index.tsx
  src/packages/icon-react/index.tsx
  src/store/application/actions.ts
  src/store/application/hooks.ts
  src/store/application/reducer.ts
Labels: UX Review Complete, review

#577 fix: pool apys
  src/app/components/trade/LiquiditySelect.tsx
  src/constants/currency.ts
  src/queries/constants.ts
  src/queries/history/index.ts
  src/queries/reward/index.ts
  src/queries/swap/index.ts
Labels: review

#575 feat: update sign-in modal to support iconex and hana
  src/app/components/WalletModal/index.tsx
Labels: UX Review Complete, review

#546 feat: 🎸 update new api and add all time rebalancing
  src/app/components/home/PositionDetailPanel.tsx
  src/queries/queryKeys.ts
  src/queries/rebalancing/index.ts
  src/store/loan/actions.ts
  src/store/loan/hooks.ts
  src/store/loan/reducer.ts
Labels: UX Review Complete, review
