Repository balancednetwork/balanced-network-interface, pull requests merged in 2021-11, with the labels that each got.

#698 Fix: update claiming ICX content
  src/app/components/home/TransactionPanel.tsx
  src/queries/history/index.ts
Labels: review, UX Review Complete

#764 implement maintenace page
  src/app/components/Layout/index.tsx
  src/app/containers/MaintenancePage/Loadable.tsx
  src/app/containers/MaintenancePage/index.tsx
  src/app/index.tsx
Labels: review

#801 Refactor/remove addresses variable
  src/app/components/trade/SwapPanel.tsx
  src/constants/pairs.ts
  src/packages/BalancedJs/addresses.ts
  src/packages/BalancedJs/contracts/IRC2.ts
  src/packages/BalancedJs/index.ts
  src/store/pool/hooks.ts
Labels: review

#791 Fix: hide vote cancelled
  src/queries/vote/index.ts
Labels: wip

#802 fix: minimum to receive
  src/types/balanced-v1-sdk/entities/trade.ts
Labels: review

#803 Configure Sejong testnet
  src/constants/currency.ts
  src/constants/tokens.ts
  src/packages/BalancedJs/addresses.ts
Labels: review
