Repository balancednetwork/balanced-network-interface, pull requests merged in 2021-08, with the labels that each got.

#592 feat: add loading animations to the vote page
  package.json
  src/app/components/ProposalInfo/index.tsx
  src/app/containers/ProposalPage/index.tsx
  src/app/containers/VotePage/index.tsx
  yarn.lock
Labels: UX Review Complete, review

#591 Fix minor issues for vote pages. Issue #588. First proposal with endD…
  src/app/components/AppBar/index.tsx
  src/app/components/ProposalInfo/index.tsx
  src/app/containers/ProposalPage/index.tsx
  src/queries/vote/index.ts
  src/types/index.ts
Labels: review

#590 fix: fix login modal layout
  src/app/components/Divider/index.tsx
  src/app/components/WalletModal/index.tsx
Labels: review, UX Review Complete

#581 fix: 🐛 can't withdraw all collateral
  src/app/components/home/LoanPanel.tsx
Labels: review

#580 Fix: centering DropdownPopper
  src/app/components/CurrencyInputPanel/index.tsx
  src/app/components/Popover/index.tsx
  src/app/components/trade/LPPanel.tsx
  src/app/components/trade/LiquiditySelect.tsx
Labels: review, UX Review Complete, Code Review Complete

#582 Feat: create tooltip without arrow and border
  src/app/components/Header/index.tsx
  src/app/components/Logo/index.tsx
  src/app/components/Popover/index.tsx
  src/app/components/Tooltip/index.tsx
Labels: review, UX Review Complete, Code Review Complete

#561 Fix: risk ratio tooltips at mobile
  src/app/components/Form/index.tsx
  src/app/components/QuestionHelper/index.tsx
  src/app/components/Tooltip/index.tsx
  src/app/components/home/PositionDetailPanel.tsx
  src/app/theme/index.tsx
Labels: review, UX Review Complete, Code Review Complete

#597 Fix: remove asset retired
  src/app/components/trade/ReturnICDSection.tsx
  src/app/containers/TradePage/index.tsx
Labels: review, UX Review Complete

#583 Fix:Ledger-integration/#574 User needs to refresh everytime connecting ledger
  src/app/components/WalletModal/index.tsx
Labels: review

#608 fix: add more vote information
  src/app/containers/ProposalPage/index.tsx
  src/queries/vote/index.ts
Labels: wip

#596 feat(swap-tab): implement ratio option component
  src/app/components/CurrencyInputPanel/index.tsx
  src/app/components/List/index.tsx
  src/app/components/Popover/index.tsx
  src/app/components/trade/SwapPanel.tsx
  src/store/swap/actions.ts
  src/store/swap/hooks.ts
  src/store/swap/reducer.ts
Labels: review, UX Review Complete, Code Review Complete

#613 fix: fix hover state of active tab
  src/app/components/Tab/index.tsx
Labels: review, UX Review Complete

#616 Fix: BALN Balance Value: Unstaking shows nowhere
  src/app/components/home/WalletPanel.tsx
Labels: review, UX Review Complete, Code Review Complete

#615 fix: voting weight
  src/packages/BalancedJs/contracts/Governance.ts
  src/queries/vote/index.ts
Labels: review, Code Review Complete

#620 Fix: reduce notification showing time
  src/store/transactions/updater.tsx
Labels: review, UX Review Complete

#618 Fix - Origination Fee
  src/app/components/home/LoanPanel.tsx
Labels: UX Review Complete

#624 feat: update the loading spinner on the trade page
  src/app/components/Spinner/index.tsx
  src/app/components/trade/SwapDescription.tsx
  src/assets/images/spinner-big.png
Labels: review

#629 Fix wording in the activity history
  src/app/components/home/TransactionPanel.tsx
Labels: review

#621 feat: add indication for claimable icx from unstaking sicx
  src/app/components/home/WalletPanel.tsx
  src/app/components/home/wallets/ICXWallet/UnstakePanel.tsx
  src/app/components/home/wallets/ICXWallet/index.tsx
  src/app/components/home/wallets/utils.tsx
Labels: wip, UX Review Complete

#483 feat: add omm markets
  src/app/components/List/index.tsx
  src/app/components/home/wallets/SendPanel.tsx
  src/app/components/trade/LPDescription.tsx
  src/app/components/trade/SupplyLiquidityModal.tsx
  src/app/components/trade/SwapPanel.tsx
  src/assets/tokens/IUSDC.svg
  src/assets/tokens/OMM.svg
  src/assets/tokens/USDS.svg
  src/constants/currency.ts
  src/packages/BalancedJs/addresses.ts
  src/packages/BalancedJs/contracts/IUSDC.ts
  src/packages/BalancedJs/contracts/OMM.ts
  src/packages/BalancedJs/contracts/USDS.ts
  src/packages/BalancedJs/index.ts
  src/store/pool/hooks.ts
Labels: blocked

#612 fix: fix tooltip font size on mobile
  src/app/components/Tooltip/index.tsx
  src/app/components/home/PositionDetailPanel.tsx
Labels: review, UX Review Complete
