Repository balancednetwork/balanced-network-interface, pull requests merged in 2022-06, with the labels that each got.

#983 feat: add user logout after an hour
  src/hooks/useLocalStorage.ts
  src/packages/icon-react/index.tsx
Labels: review, UX Review Complete

#1000 fix: show red '-' to remove added tokens
  src/app/components/SearchModal/CurrencyList.tsx
Labels: review, UX Review Complete

#994 feat: change activity history to two decimal places
  src/app/components/home/TransactionPanel.tsx
  src/utils/index.ts
Labels: review, UX Review Complete

#1006 Feat/add price info to currency selector
  src/app/components/SearchModal/CurrencyList.tsx
  src/app/theme/index.tsx
Labels: review

#1007 integrate with berlin testnet
  package.json
  src/app/components/home/RewardsPanel.tsx
  src/constants/pairs.ts
  src/constants/routing.ts
  src/constants/tokens.ts
  src/store/reward/hooks.ts
  yarn.lock
Labels: blocked, review

#770 Feat/implement staking LP token
  package.json
  src/app/components/trade/LPDescription.tsx
  src/app/components/trade/LPPanel.tsx
  src/app/components/trade/LiquidityDetails.tsx
  src/app/components/trade/StakeLPPanel.tsx
  src/app/components/trade/SupplyLiquidityModal.tsx
  src/app/components/trade/utils.tsx
  src/app/index.tsx
  src/assets/icons/arrow-line.svg
  src/constants/pairs.ts
  src/constants/routing.ts
  src/constants/tokens.ts
  src/hooks/usePools.ts
  src/hooks/useV2Pairs.ts
  src/store/configureStore.ts
  src/store/mint/hooks.tsx
  src/store/stakedLP/actions.ts
  src/store/stakedLP/hooks.ts
  src/store/stakedLP/reducer.ts
  src/types/RootState.ts
  yarn.lock
Labels: review

#982 feat/add stability fund UI
  src/app/components/Divider/index.tsx
  src/app/components/Popover/index.tsx
  src/app/components/StabilityFund/index.tsx
  src/app/components/trade/SwapPanel.tsx
  src/app/containers/TradePage/index.tsx
  src/constants/tokens.ts
  src/store/configureStore.ts
  src/store/stabilityFund/actions.ts
  src/store/stabilityFund/hooks.ts
  src/store/stabilityFund/reducer.ts
  src/types/RootState.ts
Labels: review, UX Review Complete
