Repository balancednetwork/balanced-network-interface, pull requests merged in 2022-02, with the labels that each got.

#877 fix: remove riskbar slider animation
  src/app/components/home/PositionDetailPanel.tsx
Labels: review, UX Review Complete

#878 feat: add possibility to change vote
  src/app/components/ProposalModal/index.tsx
  src/app/containers/NewProposalPage/index.tsx
  src/app/containers/ProposalPage/index.tsx
Labels: review, UX Review Complete

#840 add: optimise small device ux
  src/app/components/AppBar/index.tsx
  src/app/components/Form/index.tsx
  src/app/components/Pagination/index.tsx
  src/app/components/Panel/index.tsx
  src/app/components/SearchModal/CurrencyList.tsx
  src/app/components/Spinner/index.tsx
  src/app/components/Tooltip/index.tsx
  src/app/components/WalletModal/index.tsx
  src/app/components/home/CollateralPanel.tsx
  src/app/components/home/LoanPanel.tsx
  src/app/components/home/PositionDetailPanel.tsx
  src/app/components/home/TransactionPanel.tsx
  src/app/components/home/WalletPanel.tsx
  src/app/components/home/wallets/utils.tsx
  src/app/components/newproposal/ProposalTypesSelect.tsx
  src/app/components/newproposal/RatioInput.tsx
  src/app/components/trade/SwapDescription.tsx
  src/app/containers/ProposalPage/index.tsx
  src/app/theme/index.tsx
  src/app/theme/styled.d.ts
Labels: review, UX Review Complete

#883 Fix/withdraw liquidity tokens decimals bnusd iusdc
  src/app/components/trade/LiquidityDetails.tsx
Labels: review, UX Review Complete

#864 fix: price update
  src/app/components/trade/LiquidityDetails.tsx
  src/hooks/useLastCount.ts
  src/hooks/usePools.ts
  src/hooks/useQueuePair.ts
  src/hooks/useV2Pairs.ts
  src/packages/BalancedJs/addresses.ts
  src/packages/BalancedJs/contracts/Dex.ts
  src/packages/BalancedJs/contracts/Multicall.ts
  src/packages/BalancedJs/index.ts
  src/store/swap/hooks.ts
  src/types/balanced-v1-sdk/entities/pair.ts
Labels: review

#822 Refactor: LedgerConfirmMessage and CurrencyBalanceErrorMessage
  src/app/components/ModalContent/index.tsx
  src/app/components/ProposalModal/index.tsx
  src/app/components/home/CollateralPanel.tsx
  src/app/components/home/LoanPanel.tsx
  src/app/components/home/RewardsPanel.tsx
  src/app/components/home/wallets/BALNWallet/StakePanel.tsx
  src/app/components/home/wallets/ICXWallet/UnstakePanel.tsx
  src/app/components/home/wallets/SICXWallet/DepositPanel.tsx
  src/app/components/home/wallets/SICXWallet/UnstakePanel.tsx
  src/app/components/home/wallets/SendPanel.tsx
  src/app/components/trade/LiquidityDetails.tsx
  src/app/components/trade/SupplyLiquidityModal.tsx
  src/app/components/trade/SwapPanel.tsx
  src/app/containers/NewProposalPage/index.tsx
Labels: review, UX Review Complete, Code Review Complete

#897 feat: add plausible analytics code
  public/index.html
Labels: review, UX Review Complete

#891 Feat: implement message banner
  src/app/Message.tsx
  src/app/components/Banner/index.tsx
  src/app/components/Link/index.tsx
  src/app/index.tsx
  src/assets/icons/cross.svg
Labels: blocked, review, UX Review Complete

#890 fix: show voting progress to all users
  src/app/containers/ProposalPage/index.tsx
Labels: blocked, review, UX Review Complete

#828 Refactor/use currency amount for wallet store
  src/app/components/home/WalletPanel.tsx
  src/app/components/home/wallets/ICXWallet/UnstakePanel.tsx
  src/app/components/home/wallets/SICXWallet/DepositPanel.tsx
  src/app/components/home/wallets/SICXWallet/UnstakePanel.tsx
  src/app/components/home/wallets/SendPanel.tsx
  src/app/components/trade/LiquidityDetails.tsx
  src/app/components/trade/SupplyLiquidityModal.tsx
  src/app/components/trade/SwapDescription.tsx
  src/app/components/trade/SwapPanel.tsx
  src/hooks/usePools.ts
  src/packages/BalancedJs/contracts/Dex.ts
  src/packages/BalancedJs/contracts/IRC2.ts
  src/packages/BalancedJs/contracts/Loans.ts
  src/packages/BalancedJs/contracts/Router.ts
  src/packages/BalancedJs/contracts/Staking.ts
  src/packages/BalancedJs/contracts/sICX.ts
  src/packages/BalancedJs/index.ts
  src/store/collateral/hooks.ts
  src/store/loan/hooks.ts
  src/store/wallet/actions.ts
  src/store/wallet/hooks.ts
  src/store/wallet/reducer.ts
  src/utils/index.ts
Labels: review
