Repository balancednetwork/balanced-network-interface, pull requests merged in 2022-04, with the labels that each got.

#927 implement language selector
  src/app/components/Menu/index.tsx
  src/app/components/Modal/index.tsx
  src/app/components/Popover/index.tsx
  src/app/components/WalletModal/index.tsx
  src/hooks/useLocationLinkProps.ts
Labels: blocked, review

#942 feat: add spacing to wallet label in swap
  src/app/components/trade/SwapPanel.tsx
Labels: review, UX Review Complete

#944 Fix: remove the 5m option
  src/app/components/TradingViewChart/index.tsx
Labels: review, UX Review Complete

#845 feat: keep user signed in on refresh
  package.json
  src/hooks/useLocalStorage.ts
  src/packages/BalancedJs/contractSettings.ts
  src/packages/BalancedJs/index.ts
  src/packages/icon-react/index.tsx
  yarn.lock
Labels: review

#943 fix: prevent ledger was deactivated on balanced when user login the same wallet address on another platform
  src/app/components/home/CollateralPanel.tsx
  src/app/components/home/LoanPanel.tsx
  src/app/components/home/RewardsPanel.tsx
  src/app/components/home/wallets/BALNWallet/StakePanel.tsx
  src/app/components/home/wallets/ICXWallet/UnstakePanel.tsx
  src/app/components/home/wallets/SICXWallet/DepositPanel.tsx
  src/app/components/home/wallets/SICXWallet/UnstakePanel.tsx
  src/app/components/home/wallets/SendPanel.tsx
  src/app/components/trade/LiquidityDetails.tsx
  src/app/components/trade/SupplyLiquidityModal.tsx
  src/app/components/trade/SwapPanel.tsx
  src/app/containers/NewProposalPage/index.tsx
  src/app/containers/ProposalPage/index.tsx
  src/packages/BalancedJs/index.ts
  src/store/application/hooks.ts
Labels: review, UX Review Complete

#959 feat: show wallet button in all sizes
  src/app/components/Header/index.tsx
  src/app/components/Tooltip/index.tsx
Labels: wip
