Repository balancednetwork/balanced-network-interface, pull requests merged in 2022-03, with the labels that each got.

#882 Revert "Revert "add: optimise small device ux""
  src/app/components/AppBar/index.tsx
  src/app/components/Form/index.tsx
  src/app/components/Pagination/index.tsx
  src/app/components/Panel/index.tsx
  src/app/components/Popover/index.tsx
  src/app/components/SearchModal/CurrencyList.tsx
  src/app/components/Spinner/index.tsx
  src/app/components/Tooltip/index.tsx
  src/app/components/WalletModal/index.tsx
  src/app/components/home/CollateralPanel.tsx
  src/app/components/home/LoanPanel.tsx
  src/app/components/home/PositionDetailPanel.tsx
  src/app/components/home/TransactionPanel.tsx
  src/app/components/home/WalletPanel.tsx
  src/app/components/home/wallets/utils.tsx
  src/app/components/newproposal/ProposalTypesSelect.tsx
  src/app/components/newproposal/RatioInput.tsx
  src/app/components/trade/LPDescription.tsx
  src/app/components/trade/SwapDescription.tsx
  src/app/containers/ProposalPage/index.tsx
  src/app/theme/index.tsx
  src/app/theme/styled.d.ts
Labels: review, UX Review Complete

#887 fix: close ledger transport properly
  src/app/components/Header/index.tsx
Labels: Code Review Complete

#903 Refactor: Sometimes ledger load address list of first page on other pages
  src/app/components/WalletModal/index.tsx
  src/store/application/hooks.ts
  src/store/application/reducer.ts
Labels: review, UX Review Complete, Code Review Complete

#911 deploy airdrip page as a PR
  src/app/components/Link/index.tsx
  src/app/containers/Airdrip/Loadable.tsx
  src/app/containers/Airdrip/index.tsx
  src/app/index.tsx
  src/packages/BalancedJs/addresses.ts
  src/packages/BalancedJs/contracts/Airdrip.ts
  src/packages/BalancedJs/contracts/LiquidationDisbursement.ts
  src/packages/BalancedJs/index.ts
  src/utils/index.ts
Labels: review

#914 fix: fix heading size on claim page
  src/app/containers/Airdrip/index.tsx
Labels: review

#915 Fix: correct token symbol
  src/app/components/trade/LiquidityDetails.tsx
Labels: UX Review Complete, Code Review Complete, RTM

#895 Feat: hide pool record if base balance of a pool is too small
  src/app/components/trade/LiquidityDetails.tsx
  src/constants/index.ts
  src/hooks/useV2Pairs.ts
  src/queries/swap/index.ts
  src/store/swap/hooks.ts
  src/store/swap/trade.ts
  src/types/adapter.ts
Labels: UX Review Complete, Code Review Complete, RTM

#917 fix: remove redundant ledger confirm message
  src/app/components/home/RewardsPanel.tsx
Labels: review

#916 Feat/optimise token search
  src/app/components/SearchModal/CurrencySearch.tsx
  src/app/components/SearchModal/filtering.ts
  src/constants/tokens.ts
  src/types/balanced-sdk-core/entities/token.ts
Labels: review, UX Review Complete, Code Review Complete

#908 feat: add keyboard control to currency select
  src/app/components/List/index.tsx
  src/app/components/SearchModal/CurrencyList.tsx
  src/app/components/SearchModal/CurrencySearch.tsx
  src/hooks/useArrowControl.ts
  src/hooks/useKeyPress.ts
Labels: review, UX Review Complete, Code Review Complete

#847 Fix: update network fee logic
  src/app/components/home/RewardsPanel.tsx
  src/queries/reward/index.ts
Labels: review

#902 Fix invariant errors in Supply liquidity tab
  src/app/components/trade/LPPanel.tsx
  src/packages/BalancedJs/contracts/Dex.ts
  src/store/mint/hooks.tsx
Labels: bug, review

#896 Adjust the price chart time frames on the Trade page
  src/app/components/TradingViewChart/index.tsx
Labels: wip

#925 implement i18n
  .github/workflows/crowdin-sync.yaml
  .github/workflows/crowdin.yaml
  .gitignore
  internals/extractMessages/i18next-scanner.config.js
  internals/extractMessages/stringfyTranslations.js
  internals/generators/component/index.test.tsx.hbs
  internals/generators/component/index.ts
  internals/generators/component/index.tsx.hbs
  internals/generators/component/loadable.ts.hbs
  internals/generators/component/messages.ts.hbs
  internals/generators/container/appendRootState.hbs
  internals/generators/container/importContainerState.hbs
  internals/generators/container/index.test.tsx.hbs
  internals/generators/container/index.ts
  internals/generators/container/index.tsx.hbs
  internals/generators/container/loadable.ts.hbs
  internals/generators/container/messages.ts.hbs
  internals/generators/container/saga.ts.hbs
  internals/generators/container/selectors.ts.hbs
  internals/generators/container/slice.ts.hbs
  internals/generators/container/types.ts.hbs
  internals/generators/plopfile.ts
  internals/generators/utils/index.ts
  internals/testing/loadable.mock.tsx
  internals/testing/test-generators.ts
  internals/ts-node.tsconfig.json
  lingui.config.ts
  package.json
  src/app/components/Header/index.tsx
  src/app/components/WalletModal/index.tsx
  src/app/components/home/CollateralPanel.tsx
  src/app/components/home/LoanPanel.tsx
  src/app/components/home/PositionDetailPanel.tsx
  src/app/components/trade/LPPanel.tsx
  src/app/components/trade/LiquidityDetails.tsx
  src/app/components/trade/SwapDescription.tsx
  src/app/components/trade/SwapPanel.tsx
  src/app/containers/HomePage/index.tsx
  src/app/containers/NewProposalPage/index.tsx
  src/app/containers/ProposalPage/index.tsx
  src/app/containers/TradePage/index.tsx
  src/app/containers/VotePage/index.tsx
  src/app/index.tsx
  src/constants/locales.ts
  src/hooks/useActiveLocale.ts
  src/hooks/useParsedQueryString.tsx
  src/i18n.tsx
  src/index.tsx
  src/lib/i18n.tsx
  src/locales/.gitkeep
  src/locales/__tests__/i18n.test.ts
  src/locales/en/translation.json
  src/locales/i18n.ts
  src/locales/translations.ts
  src/locales/types.ts
  src/store/user/actions.ts
  src/store/user/hooks.tsx
  src/store/user/reducer.ts
  yarn.lock
Labels: wip

#928 Refactor routes and layout
  src/app/Routes.tsx
  src/app/containers/HomePage/index.tsx
  src/app/containers/NewProposalPage/index.tsx
  src/app/containers/ProposalPage/index.tsx
  src/app/containers/TradePage/index.tsx
  src/app/containers/VotePage/index.tsx
  src/app/index.tsx
Labels: review, Code Review Complete

#930 Add possible missing text trans
  src/app/components/trade/utils.tsx
Labels: review, Code Review Complete
