Repository balancednetwork/balanced-network-interface, pull requests merged in 2022-08, with the labels that each got.

#1053 hotfix: upgrade balanced-js version
  package.json
  yarn.lock
Labels: review

#1057 Fix: prevent wallet negative value
  src/app/components/trade/LPPanel.tsx
Labels: review

#1059 fix-slippage-tolerance
  src/app/components/SlippageSetting/index.tsx
Labels: review

#1039 Fix: update vote actions in the form [[method1, params1],...]
  src/app/containers/NewProposalPage/constant.ts
  src/app/containers/NewProposalPage/index.tsx
Labels: review

#1062 fix-rounding
  src/app/components/trade/SupplyLiquidityModal.tsx
Labels: review, UX Review Complete

#1061 feat: update v1 sdk version
  package.json
  yarn.lock
Labels: review, UX Review Complete, Code Review Complete

#1068 change-default-LP
  src/store/mint/reducer.ts
Labels: review, UX Review Complete

#1067 fix-round
  src/app/components/trade/LPDescription.tsx
Labels: review, UX Review Complete

#998 feat: add vote page enhancements
  src/app/components/AppBar/index.tsx
  src/app/containers/ProposalPage/index.tsx
Labels: review, wip, UX Review Complete
