Repository balancednetwork/balanced-network-interface, pull requests merged in 2022-01, with the labels that each got.

#850 feat: add airdrip redirect to hp
  src/app/index.tsx
Labels: review

#851 fix: Round network fees to two decimals.
  src/app/components/home/RewardsPanel.tsx
Labels: review

#782 Fix: update token addresses of DAOfund disbursement vote & refactor
  src/app/components/CurrencyInputPanel/index.tsx
  src/app/components/SearchModal/CurrencySearch.tsx
  src/app/components/SearchModal/CurrencySearchModal.tsx
  src/app/components/home/wallets/SendPanel.tsx
  src/app/components/newproposal/FundingInput.tsx
  src/app/components/trade/LPPanel.tsx
  src/app/components/trade/LiquidityDetails.tsx
  src/app/components/trade/SwapPanel.tsx
  src/app/containers/NewProposalPage/constant.ts
  src/app/containers/NewProposalPage/index.tsx
  src/app/containers/ProposalPage/Funding.tsx
  src/constants/currency.ts
  src/constants/tokens.ts
Labels: review

#853 feat: add FIN token
  src/constants/pairs.ts
  src/constants/tokens.ts
  src/packages/BalancedJs/contracts/IRC2.ts
  src/store/wallet/hooks.ts
Labels: review, Code Review Complete

#846 fix: optimize trade page to reduce api calls
  .nvmrc
  package.json
  src/app/components/WalletModal/index.tsx
  src/app/components/home/CollateralPanel.tsx
  src/app/components/home/LoanPanel.tsx
  src/app/components/home/wallets/BALNWallet/StakePanel.tsx
  src/app/components/home/wallets/SICXWallet/DepositPanel.tsx
  src/app/components/home/wallets/SICXWallet/UnstakePanel.tsx
  src/app/components/home/wallets/SendPanel.tsx
  src/app/components/trade/LiquidityDetails.tsx
  src/app/components/trade/SupplyLiquidityModal.tsx
  src/app/components/trade/SwapPanel.tsx
  src/app/index.tsx
  src/constants/misc.ts
  src/constants/routing.ts
  src/hooks/useIsWindowVisible.ts
  src/hooks/useQueuePair.ts
  src/hooks/useV2Pairs.ts
  src/packages/BalancedJs/contracts/BALN.ts
  src/packages/BalancedJs/contracts/Dex.ts
  src/packages/BalancedJs/contracts/Dividends.ts
  src/packages/BalancedJs/contracts/Governance.ts
  src/packages/BalancedJs/contracts/IRC2.ts
  src/packages/BalancedJs/contracts/Loans.ts
  src/packages/BalancedJs/contracts/Rewards.ts
  src/packages/BalancedJs/contracts/Router.ts
  src/packages/BalancedJs/contracts/Staking.ts
  src/packages/BalancedJs/contracts/contract.ts
  src/packages/BalancedJs/contracts/sICX.ts
  src/packages/BalancedJs/index.ts
  src/packages/BalancedJs/ledger.ts
  src/packages/icon-react/index.tsx
  src/store/application/actions.ts
  src/store/application/hooks.ts
  src/store/application/reducer.ts
  src/store/application/updater.ts
  src/store/transactions/actions.ts
  src/store/transactions/updater.tsx
  src/store/user/hooks.tsx
  src/store/wallet/hooks.ts
  src/types/balanced-sdk-core/constants.ts
  src/types/balanced-sdk-core/entities/fractions/fraction.ts
  src/utils/index.ts
  yarn.lock
Labels: wip

#862 fix: update liquidation price tooltip
  src/app/components/home/PositionDetailPanel.tsx
Labels: review

#867 Feat/update risk ratio bar
  src/app/components/home/PositionDetailPanel.tsx
Labels: review

#870 feat: hide liquidity details if user has no liquidity provided
  src/app/components/trade/LiquidityDetails.tsx
Labels: review, UX Review Complete
