Repository balancednetwork/balanced-network-interface, pull requests merged in 2023-03, with the labels that each got.

#1171 Add redemption content
  src/app/components/home/LoanPanel.tsx
  src/app/components/home/PositionDetailPanel.tsx
  src/queries/rebalancing/index.ts
Labels: review

#1174 Migrate backend APIs
  src/app/components/TradingViewAdvanced/api/history.ts
  src/app/components/home/RewardsPanel.tsx
  src/app/components/trade/AllPoolsPanel.tsx
  src/app/components/trade/LPDescription.tsx
  src/app/components/trade/LiquidityDetails.tsx
  src/app/components/trade/LiquidityDetails/StakeLPPanel.tsx
  src/app/components/trade/SwapDescription.tsx
  src/app/containers/HomePage/index.tsx
  src/hooks/useSort.ts
  src/queries/backendv2/index.ts
  src/queries/constants.ts
  src/queries/reward/index.ts
  src/queries/swap/index.ts
Labels: wip

#1175 Refactor charts to comply with new backend
  src/app/components/TradingViewAdvanced/api/index.ts
  src/app/components/trade/SwapDescription.tsx
  src/queries/swap/index.ts
Labels: review

#1172 Remove notification after claiming unstaked icx
  src/app/components/Header/index.tsx
Labels: review

#1161 Feat/ remove activity history
  src/app/components/Pagination/index.tsx
  src/app/components/home/BBaln/BBalnPanel.tsx
  src/app/components/home/BBaln/styledComponents.tsx
  src/app/components/home/RewardsPanel.tsx
  src/app/components/home/TransactionPanel.tsx
  src/app/components/home/sample2.json
  src/app/components/home/samples.json
Labels: wip

#1181 Fix: remove audit disclaimer from ICON bridge modal
  src/app/components/BTP/index.tsx
Labels: review, UX Review Complete

#1183 Fix/prevent opening Metamask when opening trade page
  src/app/components/BTP/BridgeWalletModal/index.tsx
  src/btp/src/connectors/ICONex/events.ts
  src/btp/src/connectors/MetaMask/index.ts
Labels: review, UX Review Complete
